title: Sae-Seul Park
logo:
description: Ph.D. Candidate at Carnegie Mellon University
theme: jekyll-theme-minimal
url: "http://sae-park.com"
google_analytics: UA-158269014-1
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
