theme: jekyll-theme-minimal
title: Sae-Seul Park
description: Assistant Professor of Strategic Management | Rotman School of Management, University of Toronto
author: Sae-Seul Park
email: saeseul.park@rotman.utoronto.ca
