theme: jekyll-theme-minimal
title: Kevin Mott
description: Assistant Professor of Finance, Teaching Stream | Rotman School of Management, University of Toronto
author: Kevin Mott
email: kevin.mott@rotman.utoronto.ca
